services:
  seata:
    hostname: seata
    image: seataio/seata-server:1.4.2
    volumes:
            - ./conf:/home/seata/config:rw
    env_file:
      - ./seata.env
    ports:
      - 0.0.0.0:8091:8091
    expose:
      - 8091
    container_name: seata
    restart: no
    command: ["/bin/sh", "-c", "ls /home/seata/config"]
    networks:
      - seata_network
      - micro_network
volumes:
  seata_data:
    name: seata_data
    driver: local

networks:
  seata_network:
    name: seata_network
    driver: bridge
  micro_network:
    external: false
    name: micro_network
    driver: bridge
