services:
  nacos_standalone:
    env_file:
      - ./nacos.env
    image: nacos/nacos-server:v1.4.4
    hostname: nacos_standalone
    container_name: nacos_standalone
    restart: no
    ports:
      - "127.0.0.1:8848:8848"
    networks:
      - nacos_network
      - micro_network
    volumes:
      - type: volume
        source: nacos_standalone_data
        target: /home/nacos
      - /opt/docker/project/nacos/logs:/home/nacos/logs
      - /opt/docker/project/nacos/conf:/home/nacos/conf:ro
volumes:
  nacos_standalone_data:
    name: nacos_standalone_data
    driver: local
networks:
  nacos_network:
    name: nacos_network
    driver: bridge
  micro_network:
    external: false
    name: micro_network
    driver: bridge

