services:
  redis:
    hostname: redis
    container_name: redis_db
    image: redis:7.2.1
    expose:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis-data
        target: /data
      - /opt/docker/project/redis/conf:/usr/local/etc/redis:ro
    ports:
      - "0.0.0.0:6379:6379"
    restart: always
    networks:
      - redis-network
      - micro-network
volumes:
  redis-data:
    name: redis-data-volume
    driver: local
networks:
  redis-network:
    name: redis-network
    driver: bridge
  micro-network:
    external: false
    driver: bridge
    name: micro-network